import type { Metadata } from "next";
import { Montserrat, Roboto_Mono } from "next/font/google";
import "./globals.css";


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat-sans",
  fallback: ["sans-serif"],
  weight: ["400", "500", "600", "700"],
});

const mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  fallback: ["monospace"],
});


export const metadata: Metadata = {
  title: "Example NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
